# This composite action is for building the node.js applications

name: Build Node Application
description: 'Composite action for installing dependencies and building Node.js applications'

inputs:
  node-version:
    description: 'The version of Node.js to use'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'

    - name: Detect Node.js project directory
      id: detect
      shell: bash
      run: |
        FILE=$(find . -type f -name "package.json")
        if [ -z "$FILE" ]; then
          echo "No package.json found"
          exit 1
        fi
        DIR=$(dirname "$FILE")
        F_NAME=$(basename "$FILE")
        echo "$DIR"
        echo "$F_NAME"
        echo "project_dir=$DIR" >> $GITHUB_OUTPUT
        echo "project_file=$F_NAME" >> $GITHUB_OUTPUT

    - name: Install dependencies and build
      shell: bash
      run: |
        cd ${{ steps.detect.outputs.project_dir }}
        npm install
        if [ -f "package-lock.json" ] || grep -q "\"build\":" package.json; then
          npm run build || echo "No build script found"
        fi


