# This is a composite action for building Python applications

description: 'Composite action for building Python applications'
name: Build Python Application

inputs:
  version:
    description: 'The version of the Python application'
    required: true
    default: '3.8'
  project_dir:
    description: 'The directory containing the Python project'
    required: true
    default: 'python'
  requirements_file:
    description: 'The requirements file (requirements.txt)'
    required: true
    default: 'requirements.txt'

runs:
  using: 'composite'
  steps:
    - name: checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python environment
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.version }}
    - name: set up python virtual environment and install dependencies
      shell: bash
      run: |
        python -m venv venv
        source venv/bin/activate
        python -m pip install --upgrade pip

        if [ -f ${{ inputs.project_dir }}/${{ inputs.requirements_file }} ]; then
          cd ${{ inputs.project_dir }}
          pip install -r ${{ inputs.requirements_file }}
        else
          echo "requirements.txt not found"; exit 1
        fi
