# This is a java project general build action
# when we have the project dir name and the project file name like pom.xml, build.gradle, etc.

name: Build Java Project general
description: 'Composite action for building Java project with dir name and file names'

inputs:
  java_version:
    description: 'The version of Java to use'
    required: true
  distribution:
    description: 'The distribution of the Java application'
    required: false
    default: 'temurin'
  project_dir:
    description: 'The directory containing the Java project source'
    required: true
  build_file:
    description: 'The main project file (pom.xml or build.gradle or others)'
    required: true

runs:
  using: 'composite'
  steps:
    - name: checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup JDK
      uses: actions/setup-java@v4
      with:
        java-version: ${{ inputs.java_version }}
        distribution: ${{ inputs.distribution }}

    - name: Cache Maven dependencies
      if: ${{ inputs.build_file == 'pom.xml' }}
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    
    - name: Cache Gradle dependencies
      if: ${{ inputs.build_file == 'build.gradle' || inputs.build_file == 'build.gradle.kts' }}
      uses: actions/cache@v4
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/build.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Build Java application
      shell: bash
      run: |
        cd ${{ inputs.project_dir }}
        if [ "${{ inputs.build_file }}" == "pom.xml" ]; then
          mvn clean package
        elif [ "${{ inputs.build_file }}" == "build.gradle" ] || [ "${{ inputs.build_file }}" == "build.gradle.kts" ]; then
          ./gradlew build
        else
          echo "No valid project file found"
          exit 1
        fi