# This is a composite action for building Java applications

name: Build Java Application
description: 'Composite action for building Java applications'

inputs:
  version:
    description: 'The version of the Java application'
    required: true
    default: '17'
  distribution:
    description: 'The distribution of the Java application'
    required: false
    default: 'temurin'

runs:
  using: 'composite'
  steps:
    - name: checkout code
      uses: actions/checkout@v3
      
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: ${{ inputs.version }}
        distribution: ${{ inputs.distribution }}

    - name: install dependencies and build Java application
      shell: bash
      run: |
        if [ -f java/pom.xml ]; then
          cd java
          mvn clean install
        else
          echo "No build file found (pom.xml or build.gradle)"
        fi
