# This is a Java build and version bump workflow

name: Java Build and Version Bump

on:
    workflow_call:
        inputs:
            version:
                description: 'The version of the Java application'
                required: true
                type: string
            distribution:
                description: 'The distribution of the Java application (if applicable)'
                required: true
                type: string
            project_dir:
                description: 'The directory containing the Java project'
                required: true
                type: string
            project_file:
                description: 'The main project file (pom.xml or build.gradle)'
                required: true
                type: string
            user_name:
                description: 'The name of the user making the changes'
                required: false
                default: 'ex'
                type: string
            user_email:
                description: 'The email of the user making the changes'
                required: false
                default: 'ex123@gmail.com'
                type: string

jobs:
    get-version: # Get the current version of pom.xml 
        runs-on: ubuntu-latest
        outputs:
            VERSION: ${{ steps.get-version.outputs.VERSION }}
        steps:
            - name: Checkout caller and reusable code
              uses: gitpranay5/tm-reusable/actions/checkout-caller-reusable@main
              with:
                repository: gitpranay5/tm-reusable
                ref: main

            - name: Get current version from pom.xml
              id: get-version
              run: |
                chmod +x tm-reusable/scripts/get-pom-version.sh
                VERSION=$(./tm-reusable/scripts/get-pom-version.sh "${{ inputs.project_dir }}" "${{ inputs.project_file }}" )
                echo "VERSION=$VERSION"
                echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

    build-java: # Build the Java application
        runs-on: ubuntu-latest
        needs: get-version
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Build Java application
              uses: gitpranay5/tm-reusable/actions/build-java@main
              with:
                version: ${{ inputs.version }}
                distribution: ${{ inputs.distribution }}
                project_dir: ${{ inputs.project_dir }}
                project_file: ${{ inputs.project_file }}
                
            - name: Upload Java artifacts
              uses: actions/upload-artifact@v4
              with:
                name: ${{ inputs.project_dir }}-artifact-${{ needs.get-version.outputs.VERSION }}
                path: ${{ inputs.project_dir }}/target/*.jar

    bump-pom-version: # Bump the version in pom.xml in branches
        runs-on: ubuntu-latest
        needs: get-version
        env:
          CURRENT_VERSION: ${{ needs.get-version.outputs.VERSION }}
        steps:
            - name: Checkout code
              uses: gitpranay5/tm-reusable/actions/checkout-caller-reusable@main
              with:
                repository: gitpranay5/tm-reusable
                ref: main

            - name: Bump version in pom.xml
              id: bump-version
              run: |
                chmod +x tm-reusable/scripts/bump-pom-version.sh
                NEW_VERSION=$(./tm-reusable/scripts/bump-pom-version.sh $CURRENT_VERSION )
                echo "NEW_VERSION=$NEW_VERSION"
                echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
                cd ${{ inputs.project_dir }} || exit 0
                mvn versions:set -DnewVersion="$NEW_VERSION" -DgenerateBackupPoms=false
            
           
           # - name: Commit and push changes
           #   if: github.ref != 'refs/heads/main' || github.event_name == 'pull_request'
           #   run: |
           #     cd java || exit 0
           #     git fetch origin ${{ github.head_ref }}
           #     git checkout ${{ github.head_ref }}
           #     git config --global user.email "ex@gmail.com"
           #     git config --global user.name "Pranay Jujjuri"
           #     git add pom.xml
           #     git commit -m "Bump version to $NEW_VERSION" || echo "No changes to commit"
           #     git push origin ${{ github.head_ref }}

            - name: Bump pom version directly to main branch on a push to main
              if: github.event_name == 'push' && github.ref == 'refs/heads/main'
              run: |
                cd ${{ inputs.project_dir }} || exit 0
                git config --global user.email "${{ inputs.user_email }}"
                git config --global user.name "${{ inputs.user_name }}"
                git add pom.xml
                git commit -m "Bumpped the version to $NEW_VERSION" || echo "No changes to commit"
                git push origin main
            
            - name: Adding git tag and pushing
              if: github.event_name == 'push' && github.ref == 'refs/heads/main'
              run: |
                cd ${{ inputs.project_dir }} || exit 0
                git tag "v$NEW_VERSION"
                git push origin "v$NEW_VERSION"
