# Code Quality reusable workflow
name: SonarQube Code Quality

on:
  workflow_call:
    secrets:
        SONAR_TOKEN:
          description: "SonarQube authentication token"
          required: true
    inputs:
      service_config_file:
        description: "Path to the service config file"
        required: true
        type: string
      service_name:
        description: "The name of the service"
        required: true
        type: string

jobs:
  sonarqube-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache SonarQube Scanner
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar-${{ hashFiles('**/*.gradle*', '**/pom.xml', '**/package-lock.json', '**/yarn.lock', '**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-sonar-

      - name: Run SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v5
        with:
          projectBaseDir: ${{ inputs.source_dir }}
          args: >
            -Dsonar.projectKey=${{ inputs.project_key }}
            -Dsonar.organization=${{ inputs.organization }}
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}